version: '3'
services:
  ##################################################################
  event:
    build: 
      context: ./
      ### Enbale for python2 and comment out "dockerfile: ./build/py3/Dockerfile"
      # dockerfile: ./build/py2/Dockerfile 
      ### Enable for python3 and comment out "dockerfile: ./build/py2/Dockerfile"
      dockerfile: ./build/py3/Dockerfile
    volumes:
      - ./shotgunEvents/src:/event
      - ./plugins:/event/plugins
      - ./log:/event/log
      - ./shotgunEventDaemon.conf:/event/shotgunEventDaemon.conf
    env_file:
      - env/event-variables.env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "2g"
        max-file: "20"
